### ISSUE TITLE
SES webhooks not coming through

### ISSUE THREAD

**Issue by ryanhungate** [spatie/mailcoach-vapor#3]
Hey have you ever gotten things "verified" where the hook comes through for verification, but no "open" or "click" events come through at all? 

I've got the settings in the campaign set to track, I've also got my event notifications for all the proper click, open, bounce etc, but we're not seeing anything come through for opens or clicks. I'm getting the email tests, but nothing is being tracked yet.

**Comment by riasvdv** [comment]
Are you sending the campaign when testing? Or using the "send test" functionality? Open & click tracking are only enabled when actually sending the campaign.

**Comment by ryanhungate** [comment]
@riasvdv I don't know how I didn't see this response earlier - I apologize... but this is on a legit campaign. We're seeing 0's everywhere which leads me to believe that it's not set up properly. I'll go through the setup tutorial again to verify everything was done properly but I could have swore I did this line by line the right way. If you've verified that it's working on Vapor that's all i needed to know - or if it's a bug somewhere only on the vapor version?
