### ISSUE TITLE
Uploading images won't work with unlayer editor. 

### ISSUE THREAD

**Issue by ChrisTravPRO** [spatie/mailcoach-vapor#4]
Uploading images won't work with unlayer editor. 

In my network tab the error Reading 'Exif data is not supported by this PHP installation'

I guessed vapor doesn't meet the requirements of spatie.be/laravel-medialibrary. 
https://spatie.be/docs/laravel-medialibrary/v9/requirements

I altered the dockerfile to get rid of this error. 

```bash
FROM laravelphp/vapor:php80

RUN apk --update add ffmpeg


COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd exif

COPY . /var/task
```

Is this the correct way of tackling the problem? 

If there is a better solution or any other things that are wise to add to the dockerfile to get mailcoach correctly working i would like to know.

**Comment by riasvdv** [comment]
Looks like a good solution! I've added it to the Docker files.
